### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by harryyuanfeng** [deepinstruction/deepnude_official#3]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by deeppppp** [comment]
pip install opencv-python

will install the required module.

**Comment by harryyuanfeng** [comment]
ERROR: matplotlib 1.3.1 requires nose, which is not installed.
ERROR: matplotlib 1.3.1 requires tornado, which is not installed.
Installing collected packages: numpy, opencv-python
  Found existing installation: numpy 1.8.0rc1
ERROR: Cannot uninstall 'numpy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by harryyuanfeng** [comment]
same error after

pip install opencv-python

**Comment by truethug** [comment]
export PYTHONPATH=<path to your install folder>

**Comment by SunnerLi** [comment]
Hi @harryyuanfeng ,
I think you should install the OpenCV to deal with image process.
If you use Anaconda to run the code,
you can install the OpenCV from conda.
Open your terminal and type
```
conda install -c menpo opencv
```
Recently, I install the OpenCV from scratch Ubuntu system,
and successfully install as well via this command.
Hope this information can help you.

**Comment by harryyuanfeng** [comment]
Thanks for @SunnerLi 's help

Now I am getting new error:


`
(base) yuanfengsMini2:deepnude_official yuanfengfeng$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from run import process
  File "/Users/yuanfengfeng/Documents/deepnude_official/run.py", line 4, in <module>
    from gan import DataLoader, DeepModel, tensor2im
  File "/Users/yuanfengfeng/Documents/deepnude_official/gan.py", line 4, in <module>
    import torchvision.transforms as transforms
ModuleNotFoundError: No module named 'torchvision'
`

**Comment by harryyuanfeng** [comment]
ok Get the previous one resolved by:

`
pip install torchvision
`

 Now it seems missing files:

`
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cm.lib'
`

**Comment by harryyuanfeng** [comment]
Ok. Get the previous resolved as well by executing command from this post. 

https://github.com/deepinstruction/deepnude_official/issues/5

**Comment by harryyuanfeng** [comment]
Now I am getting:

`
ValueError: too many values to unpack (expected 2)
`

**Comment by harryyuanfeng** [comment]
Full error codes

`
(base) yuanfengsMini2:deepnude_official yuanfengfeng$ python3 main.py
libpng warning: iCCP: known incorrect sRGB profile
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Executing phase: mask_to_maskref
Executing phase: maskref_to_maskdet
Executing phase: maskdet_to_maskfin
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 21, in main
    watermark = process(dress)
  File "/Users/yuanfengfeng/Documents/deepnude_official/run.py", line 144, in process
    maskfin = create_maskfin(maskref, maskdet)
  File "/Users/yuanfengfeng/Documents/deepnude_official/opencv_transform/maskdet_to_maskfin.py", line 34, in create_maskfin
    bodypart_list = extractAnnotations(maskdet);
  File "/Users/yuanfengfeng/Documents/deepnude_official/opencv_transform/maskdet_to_maskfin.py", line 101, in extractAnnotations
    tits_list = findBodyPart(maskdet, "tit")
  File "/Users/yuanfengfeng/Documents/deepnude_official/opencv_transform/maskdet_to_maskfin.py", line 168, in findBodyPart
    contours, hierarchy = cv2.findContours(color_mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)
`

**Comment by harryyuanfeng** [comment]
I replaced with another image now I am getting something different:

`
(base) yuanfengsMini2:deepnude_official yuanfengfeng$ python3 main.py
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Executing phase: mask_to_maskref
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 21, in main
    watermark = process(dress)
  File "/Users/yuanfengfeng/Documents/deepnude_official/run.py", line 140, in process
    maskref = create_maskref(mask, correct)
  File "/Users/yuanfengfeng/Documents/deepnude_official/opencv_transform/mask_to_maskref.py", line 37, in create_maskref
    res1 = cv2.bitwise_and(cv_correct, cv_correct, mask = green_mask_inv)
cv2.error: OpenCV(3.4.2) /opt/concourse/worker/volumes/live/9523d527-1b9e-48e0-7ed0-a36adde286f0/volume/opencv-suite_1535558719691/work/modules/core/src/arithm.cpp:241: error: (-215:Assertion failed) (mtype == 0 || mtype == 1) && _mask.sameSize(*psrc1) in function 'binary_op'

`

**Comment by harryyuanfeng** [comment]
change image to 512 * 512 pixels. 

Now I am getting:

`
AttributeError: 'NoneType' object has no attribute 'shape'
`

**Comment by SunnerLi** [comment]
Hi @harryyuanfeng ,
Unfortunately, these error might come from different cases.
Maybe we should check if the image is actually loaded into the program.
As you mentioned, 
```
AttributeError: 'NoneType' object has no attribute 'shape'
```
this error might occur since the image isn't load correctly,
and the program call `np.shape(img)` (But img is None).

**Comment by SunnerLi** [comment]
Hi @harryyuanfeng ,
The other error can refer to #10

**Comment by apexkid** [comment]
Provide requirements.txt please.

**Comment by yonghenghuanmie** [comment]
> 
> 
> change image to 512 * 512 pixels.
> 
> Now I am getting:
> 
> `AttributeError: 'NoneType' object has no attribute 'shape'`

dress = cv2.imread("input.png") in main.py:18
Maybe you give a wrong filename or suffix.

**Comment by harryyuanfeng** [comment]
> > change image to 512 * 512 pixels.
> > Now I am getting:
> > `AttributeError: 'NoneType' object has no attribute 'shape'`
> 
> dress = cv2.imread("input.png") in main.py:18
> Maybe you give a wrong filename or suffix.

Yes. This is due to a typo in the file name. 

But after correct the file name, I am still getting. 

ValueError: too many values to unpack (expected 2)

And My image size is 512 * 512 pixels

Anything wrong?

![Screen Shot 2019-07-06 at 2 36 18 PM](https://user-images.githubusercontent.com/4098187/60759980-6fa1e780-9ffb-11e9-8a39-d9c404853cc7.png)

**Comment by harryyuanfeng** [comment]
Getting same error `ValueError: too many values to unpack (expected 2)`

even with the repo input.png image. 

https://raw.githubusercontent.com/deepinstruction/deepnude_official/master/input.png

**Comment by harryyuanfeng** [comment]
ok. 

This PR/Commit, 

https://github.com/deepinstruction/deepnude_official/commit/b8a67691847f7b872be633a8fb50a1c324f26b7f

fixed:

`ValueError: too many values to unpack (expected 2)`

I have tested in mac python3

**Comment by AlexBass99** [comment]
I tried everything you said and nothing worked, I have installed cv2 module but the message is still appearing
![2019-07-07_18-05-28](https://user-images.githubusercontent.com/45899795/60771019-e1ecf780-a0e1-11e9-91aa-44f20732f5a7.png)
![2019-07-07_18-06-16](https://user-images.githubusercontent.com/45899795/60771025-ee715000-a0e1-11e9-9f12-9cdb923ab66e.png)

**Comment by harryyuanfeng** [comment]
> I tried everything you said and nothing worked, I have installed cv2 module but the message is still appearing
> ![2019-07-07_18-05-28](https://user-images.githubusercontent.com/45899795/60771019-e1ecf780-a0e1-11e9-91aa-44f20732f5a7.png)
> ![2019-07-07_18-06-16](https://user-images.githubusercontent.com/45899795/60771025-ee715000-a0e1-11e9-9f12-9cdb923ab66e.png)

Have you tried:

`conda install -c menpo opencv`

**Comment by AlexBass99** [comment]
yes, I tried that, and this happens
![2019-07-07_18-51-45](https://user-images.githubusercontent.com/45899795/60771425-48751400-a0e8-11e9-99a8-c135c70dbe1e.png)
